/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Parking_managment_nidhal_ (void)
{
  GtkWidget *Parking_managment_nidhal_;
  GtkWidget *notebook1;
  GtkWidget *fixed1;
  GtkWidget *label119;
  GtkWidget *image1;
  GtkWidget *label32;
  GtkWidget *Display;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label154;
  GtkWidget *Delete;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image9;
  GtkWidget *label140;
  GtkWidget *Modify;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image10;
  GtkWidget *label141;
  GtkWidget *Add;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image8;
  GtkWidget *label139;
  GtkWidget *Parking_managment;
  GtkWidget *fixed7;
  GtkWidget *textentrynidhal1;
  GtkWidget *textentrynidhal3;
  GtkWidget *textentrynidhal6;
  GtkWidget *textentrynidhal7;
  GtkObject *spinnidhal5_adj;
  GtkWidget *spinnidhal5;
  GtkWidget *image2;
  GtkWidget *label155;
  GtkWidget *hbox14;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *textentrynidhal2;
  GtkWidget *label23;
  GtkWidget *Add_parking;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image7;
  GtkWidget *label138;
  GtkWidget *comboboxnidhal4;
  GList *comboboxnidhal4_items = NULL;
  GtkWidget *entry34;
  GtkWidget *label118;
  GtkWidget *label2;
  GtkWidget *fixed12;
  GtkWidget *label120;
  GtkWidget *label97;
  GtkWidget *entry25;
  GtkWidget *image3;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *treeview1;
  GtkWidget *hbox15;
  GtkWidget *checkbutton7;
  GtkWidget *hbox16;
  GtkWidget *checkbutton8;
  GtkWidget *hbox17;
  GtkWidget *checkbutton9;
  GtkWidget *hbox18;
  GtkWidget *checkbutton10;
  GtkWidget *combo5;
  GList *combo5_items = NULL;
  GtkWidget *entry29;
  GtkWidget *Search;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image16;
  GtkWidget *label156;
  GtkWidget *label3;
  GtkWidget *fixed16;
  GtkWidget *fixed17;
  GtkWidget *label135;
  GtkWidget *label134;
  GtkWidget *fixed20;
  GtkWidget *label159;
  GtkWidget *entry30;
  GtkWidget *image19;
  GtkWidget *entry31;
  GtkWidget *entry32;
  GtkWidget *treeview4;
  GtkWidget *hbox21;
  GtkWidget *checkbutton11;
  GtkWidget *hbox22;
  GtkWidget *checkbutton12;
  GtkWidget *hbox23;
  GtkWidget *checkbutton13;
  GtkWidget *hbox24;
  GtkWidget *checkbutton14;
  GtkWidget *combo6;
  GList *combo6_items = NULL;
  GtkWidget *entry33;
  GtkWidget *Search_parking;
  GtkWidget *alignment15;
  GtkWidget *hbox25;
  GtkWidget *image22;
  GtkWidget *label163;
  GtkWidget *button20;
  GtkWidget *alignment13;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label161;
  GtkWidget *label124;
  GtkWidget *fixed11;
  GtkWidget *label123;
  GtkWidget *image6;
  GtkWidget *fixed13;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry21;
  GtkWidget *entry22;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label70;
  GtkWidget *hbox13;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *combo_entry1;
  GtkWidget *label79;
  GtkWidget *label78;
  GtkWidget *label71;
  GtkWidget *label77;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *Modify_parking;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image14;
  GtkWidget *label145;
  GtkWidget *label6;
  GtkWidget *fixed18;
  GtkWidget *label149;
  GtkWidget *label147;
  GtkWidget *combo3;
  GtkWidget *combo_entry3;
  GtkWidget *label148;
  GtkWidget *combo4;
  GtkWidget *entry26;
  GtkWidget *treeview5;
  GtkWidget *Assign;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label157;
  GtkWidget *Remove;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label158;
  GtkWidget *label146;
  GtkWidget *fixed19;
  GtkWidget *treeview3;
  GtkWidget *label164;
  GtkWidget *label150;

  Parking_managment_nidhal_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Parking_managment_nidhal_), _("window"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Parking_managment_nidhal_), notebook1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed1);

  label119 = gtk_label_new (_("label119"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed1), label119, 232, 656);
  gtk_widget_set_size_request (label119, 57, 17);

  image1 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 232, 160);
  gtk_widget_set_size_request (image1, 192, 200);
  gtk_misc_set_alignment (GTK_MISC (image1), 1, 1);

  label32 = gtk_label_new (_("Parking Managment"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed1), label32, 848, 16);
  gtk_widget_set_size_request (label32, 152, 16);

  Display = gtk_button_new ();
  gtk_widget_show (Display);
  gtk_fixed_put (GTK_FIXED (fixed1), Display, 872, 184);
  gtk_widget_set_size_request (Display, 112, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (Display), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label154 = gtk_label_new_with_mnemonic (_("Display"));
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (hbox9), label154, FALSE, FALSE, 0);

  Delete = gtk_button_new ();
  gtk_widget_show (Delete);
  gtk_fixed_put (GTK_FIXED (fixed1), Delete, 872, 312);
  gtk_widget_set_size_request (Delete, 112, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Delete), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image9 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox3), image9, FALSE, FALSE, 0);

  label140 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label140);
  gtk_box_pack_start (GTK_BOX (hbox3), label140, FALSE, FALSE, 0);

  Modify = gtk_button_new ();
  gtk_widget_show (Modify);
  gtk_fixed_put (GTK_FIXED (fixed1), Modify, 872, 440);
  gtk_widget_set_size_request (Modify, 112, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Modify), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox4), image10, FALSE, FALSE, 0);

  label141 = gtk_label_new_with_mnemonic (_("Modify"));
  gtk_widget_show (label141);
  gtk_box_pack_start (GTK_BOX (hbox4), label141, FALSE, FALSE, 0);

  Add = gtk_button_new ();
  gtk_widget_show (Add);
  gtk_fixed_put (GTK_FIXED (fixed1), Add, 872, 72);
  gtk_widget_set_size_request (Add, 112, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (Add), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox2), image8, FALSE, FALSE, 0);

  label139 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (hbox2), label139, FALSE, FALSE, 0);

  Parking_managment = gtk_label_new (_("Parking Managment"));
  gtk_widget_show (Parking_managment);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Parking_managment);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  textentrynidhal1 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal1);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal1, 104, 24);
  gtk_widget_set_size_request (textentrynidhal1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal1), 8226);

  textentrynidhal3 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal3);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal3, 104, 104);
  gtk_widget_set_size_request (textentrynidhal3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal3), 8226);

  textentrynidhal6 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal6);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal6, 112, 224);
  gtk_widget_set_size_request (textentrynidhal6, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal6), 8226);

  textentrynidhal7 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal7);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal7, 112, 264);
  gtk_widget_set_size_request (textentrynidhal7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal7), 8226);

  spinnidhal5_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinnidhal5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinnidhal5_adj), 1, 0);
  gtk_widget_show (spinnidhal5);
  gtk_fixed_put (GTK_FIXED (fixed7), spinnidhal5, 112, 184);
  gtk_widget_set_size_request (spinnidhal5, 160, 27);

  image2 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed7), image2, 920, 64);
  gtk_widget_set_size_request (image2, 192, 200);
  gtk_misc_set_alignment (GTK_MISC (image2), 1, 1);

  label155 = gtk_label_new (_("Add a parking"));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed7), label155, 872, 8);
  gtk_widget_set_size_request (label155, 112, 16);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_fixed_put (GTK_FIXED (fixed7), hbox14, 736, 528);
  gtk_widget_set_size_request (hbox14, 32, 16);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Confirm"));
  gtk_widget_show (radiobutton7);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton7, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Cancel"));
  gtk_widget_show (radiobutton8);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton8, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  label24 = gtk_label_new (_("parking_name"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 8, 72);
  gtk_widget_set_size_request (label24, 96, 16);

  label25 = gtk_label_new (_("address"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 16, 104);
  gtk_widget_set_size_request (label25, 64, 16);

  label26 = gtk_label_new (_("parking_type"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 0, 152);
  gtk_widget_set_size_request (label26, 96, 16);

  label27 = gtk_label_new (_("ability"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed7), label27, 24, 192);
  gtk_widget_set_size_request (label27, 56, 16);

  label29 = gtk_label_new (_("pricing"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 24, 272);
  gtk_widget_set_size_request (label29, 56, 16);

  label28 = gtk_label_new (_("opening_hours"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed7), label28, 0, 232);
  gtk_widget_set_size_request (label28, 104, 16);

  textentrynidhal2 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal2);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal2, 112, 64);
  gtk_widget_set_size_request (textentrynidhal2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal2), 8226);

  label23 = gtk_label_new (_("parking_ID"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed7), label23, 16, 32);
  gtk_widget_set_size_request (label23, 72, 16);

  Add_parking = gtk_button_new ();
  gtk_widget_show (Add_parking);
  gtk_fixed_put (GTK_FIXED (fixed7), Add_parking, 760, 576);
  gtk_widget_set_size_request (Add_parking, 88, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Add_parking), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox1), image7, FALSE, FALSE, 0);

  label138 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (hbox1), label138, FALSE, FALSE, 0);

  comboboxnidhal4 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (comboboxnidhal4)->popwin),
                     "GladeParentKey", comboboxnidhal4);
  gtk_widget_show (comboboxnidhal4);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxnidhal4, 104, 144);
  gtk_widget_set_size_request (comboboxnidhal4, 187, 27);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxnidhal4), 3);
  gtk_combo_set_value_in_list (GTK_COMBO (comboboxnidhal4), TRUE, TRUE);
  gtk_combo_set_case_sensitive (GTK_COMBO (comboboxnidhal4), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (comboboxnidhal4), TRUE);
  comboboxnidhal4_items = g_list_append (comboboxnidhal4_items, (gpointer) _("Outside"));
  comboboxnidhal4_items = g_list_append (comboboxnidhal4_items, (gpointer) _("Interior"));
  comboboxnidhal4_items = g_list_append (comboboxnidhal4_items, (gpointer) _("Covered"));
  gtk_combo_set_popdown_strings (GTK_COMBO (comboboxnidhal4), comboboxnidhal4_items);
  g_list_free (comboboxnidhal4_items);

  entry34 = GTK_COMBO (comboboxnidhal4)->entry;
  gtk_widget_show (entry34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  label118 = gtk_label_new (_("label118"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed7), label118, 104, 600);
  gtk_widget_set_size_request (label118, 472, 32);

  label2 = gtk_label_new (_("Add a parking"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  label120 = gtk_label_new (_("label120"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed12), label120, 256, 656);
  gtk_widget_set_size_request (label120, 57, 17);

  label97 = gtk_label_new (_("Parking display"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed12), label97, 800, 8);
  gtk_widget_set_size_request (label97, 120, 16);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed12), entry25, 720, 64);
  gtk_widget_set_size_request (entry25, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  image3 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed12), image3, 96, 176);
  gtk_widget_set_size_request (image3, 200, 200);
  gtk_misc_set_alignment (GTK_MISC (image3), 1, 1);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed12), entry27, 392, 56);
  gtk_widget_set_size_request (entry27, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed12), entry28, 432, 112);
  gtk_widget_set_size_request (entry28, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview1, 568, 240);
  gtk_widget_set_size_request (treeview1, 344, 240);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox15, 280, 64);
  gtk_widget_set_size_request (hbox15, 16, 16);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("parking_ID"));
  gtk_widget_show (checkbutton7);
  gtk_box_pack_start (GTK_BOX (hbox15), checkbutton7, FALSE, FALSE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox16, 296, 120);
  gtk_widget_set_size_request (hbox16, 16, 16);

  checkbutton8 = gtk_check_button_new_with_mnemonic (_("parking_name"));
  gtk_widget_show (checkbutton8);
  gtk_box_pack_start (GTK_BOX (hbox16), checkbutton8, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox17, 624, 72);
  gtk_widget_set_size_request (hbox17, 16, 16);

  checkbutton9 = gtk_check_button_new_with_mnemonic (_("address"));
  gtk_widget_show (checkbutton9);
  gtk_box_pack_start (GTK_BOX (hbox17), checkbutton9, FALSE, FALSE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox18, 640, 120);
  gtk_widget_set_size_request (hbox18, 16, 16);

  checkbutton10 = gtk_check_button_new_with_mnemonic (_("parking_type"));
  gtk_widget_show (checkbutton10);
  gtk_box_pack_start (GTK_BOX (hbox18), checkbutton10, FALSE, FALSE, 0);

  combo5 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo5)->popwin),
                     "GladeParentKey", combo5);
  gtk_widget_show (combo5);
  gtk_fixed_put (GTK_FIXED (fixed12), combo5, 752, 112);
  gtk_widget_set_size_request (combo5, 187, 27);
  gtk_container_set_border_width (GTK_CONTAINER (combo5), 3);
  gtk_combo_set_value_in_list (GTK_COMBO (combo5), TRUE, TRUE);
  gtk_combo_set_case_sensitive (GTK_COMBO (combo5), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo5), TRUE);
  combo5_items = g_list_append (combo5_items, (gpointer) _("Outside"));
  combo5_items = g_list_append (combo5_items, (gpointer) _("Interior"));
  combo5_items = g_list_append (combo5_items, (gpointer) _("Covered"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo5), combo5_items);
  g_list_free (combo5_items);

  entry29 = GTK_COMBO (combo5)->entry;
  gtk_widget_show (entry29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  Search = gtk_button_new ();
  gtk_widget_show (Search);
  gtk_fixed_put (GTK_FIXED (fixed12), Search, 1000, 72);
  gtk_widget_set_size_request (Search, 96, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (Search), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox10), image16, FALSE, FALSE, 0);

  label156 = gtk_label_new_with_mnemonic (_("Search"));
  gtk_widget_show (label156);
  gtk_box_pack_start (GTK_BOX (hbox10), label156, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Parking display"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed16);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_fixed_put (GTK_FIXED (fixed16), fixed17, 0, 0);
  gtk_widget_set_size_request (fixed17, 0, 0);

  label135 = gtk_label_new (_("label120"));
  gtk_widget_show (label135);
  gtk_fixed_put (GTK_FIXED (fixed17), label135, 256, 656);
  gtk_widget_set_size_request (label135, 57, 17);

  label134 = gtk_label_new (_("Delete a parking"));
  gtk_widget_show (label134);
  gtk_fixed_put (GTK_FIXED (fixed17), label134, 800, 8);
  gtk_widget_set_size_request (label134, 120, 16);

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_fixed_put (GTK_FIXED (fixed17), fixed20, 0, 0);
  gtk_widget_set_size_request (fixed20, 0, 0);

  label159 = gtk_label_new (_("label120"));
  gtk_widget_show (label159);
  gtk_fixed_put (GTK_FIXED (fixed20), label159, 256, 656);
  gtk_widget_set_size_request (label159, 57, 17);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed20), entry30, 720, 64);
  gtk_widget_set_size_request (entry30, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  image19 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed20), image19, 96, 176);
  gtk_widget_set_size_request (image19, 200, 200);
  gtk_misc_set_alignment (GTK_MISC (image19), 1, 1);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed20), entry31, 392, 56);
  gtk_widget_set_size_request (entry31, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  entry32 = gtk_entry_new ();
  gtk_widget_show (entry32);
  gtk_fixed_put (GTK_FIXED (fixed20), entry32, 416, 112);
  gtk_widget_set_size_request (entry32, 176, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 8226);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed20), treeview4, 568, 240);
  gtk_widget_set_size_request (treeview4, 344, 240);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_fixed_put (GTK_FIXED (fixed20), hbox21, 280, 64);
  gtk_widget_set_size_request (hbox21, 16, 16);

  checkbutton11 = gtk_check_button_new_with_mnemonic (_("parking_ID"));
  gtk_widget_show (checkbutton11);
  gtk_box_pack_start (GTK_BOX (hbox21), checkbutton11, FALSE, FALSE, 0);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox22);
  gtk_fixed_put (GTK_FIXED (fixed20), hbox22, 296, 120);
  gtk_widget_set_size_request (hbox22, 16, 16);

  checkbutton12 = gtk_check_button_new_with_mnemonic (_("parking_name"));
  gtk_widget_show (checkbutton12);
  gtk_box_pack_start (GTK_BOX (hbox22), checkbutton12, FALSE, FALSE, 0);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox23);
  gtk_fixed_put (GTK_FIXED (fixed20), hbox23, 624, 72);
  gtk_widget_set_size_request (hbox23, 16, 16);

  checkbutton13 = gtk_check_button_new_with_mnemonic (_("address"));
  gtk_widget_show (checkbutton13);
  gtk_box_pack_start (GTK_BOX (hbox23), checkbutton13, FALSE, FALSE, 0);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox24);
  gtk_fixed_put (GTK_FIXED (fixed20), hbox24, 640, 120);
  gtk_widget_set_size_request (hbox24, 16, 16);

  checkbutton14 = gtk_check_button_new_with_mnemonic (_("parking_type"));
  gtk_widget_show (checkbutton14);
  gtk_box_pack_start (GTK_BOX (hbox24), checkbutton14, FALSE, FALSE, 0);

  combo6 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo6)->popwin),
                     "GladeParentKey", combo6);
  gtk_widget_show (combo6);
  gtk_fixed_put (GTK_FIXED (fixed20), combo6, 760, 112);
  gtk_widget_set_size_request (combo6, 187, 27);
  gtk_container_set_border_width (GTK_CONTAINER (combo6), 3);
  gtk_combo_set_value_in_list (GTK_COMBO (combo6), TRUE, TRUE);
  gtk_combo_set_case_sensitive (GTK_COMBO (combo6), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo6), TRUE);
  combo6_items = g_list_append (combo6_items, (gpointer) _("Outside"));
  combo6_items = g_list_append (combo6_items, (gpointer) _("Interior"));
  combo6_items = g_list_append (combo6_items, (gpointer) _("Covered"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo6), combo6_items);
  g_list_free (combo6_items);

  entry33 = GTK_COMBO (combo6)->entry;
  gtk_widget_show (entry33);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry33), 8226);

  Search_parking = gtk_button_new ();
  gtk_widget_show (Search_parking);
  gtk_fixed_put (GTK_FIXED (fixed20), Search_parking, 1000, 72);
  gtk_widget_set_size_request (Search_parking, 96, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (Search_parking), alignment15);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox25);

  image22 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox25), image22, FALSE, FALSE, 0);

  label163 = gtk_label_new_with_mnemonic (_("Search"));
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox25), label163, FALSE, FALSE, 0);

  button20 = gtk_button_new ();
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed20), button20, 1008, 128);
  gtk_widget_set_size_request (button20, 90, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button20), alignment13);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label161 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label161);
  gtk_box_pack_start (GTK_BOX (hbox19), label161, FALSE, FALSE, 0);

  label124 = gtk_label_new (_("Delete a parking"));
  gtk_widget_show (label124);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label124);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  label123 = gtk_label_new (_("label123"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed11), label123, 32, 696);
  gtk_widget_set_size_request (label123, 57, 17);

  image6 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed11), image6, 112, 152);
  gtk_widget_set_size_request (image6, 176, 192);
  gtk_misc_set_alignment (GTK_MISC (image6), 1, 1);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_fixed_put (GTK_FIXED (fixed11), fixed13, 424, 24);
  gtk_widget_set_size_request (fixed13, 776, 568);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed13), entry17, 104, 24);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed13), entry18, 104, 64);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed13), entry19, 104, 104);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed13), entry21, 104, 224);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed13), entry22, 104, 264);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  spinbutton2_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton2, 104, 184);
  gtk_widget_set_size_request (spinbutton2, 152, 32);

  label70 = gtk_label_new (_("Modify a parking"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed13), label70, 416, 0);
  gtk_widget_set_size_request (label70, 120, 16);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_fixed_put (GTK_FIXED (fixed13), hbox13, 624, 400);
  gtk_widget_set_size_request (hbox13, 32, 16);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Confirm"));
  gtk_widget_show (radiobutton5);
  gtk_box_pack_start (GTK_BOX (hbox13), radiobutton5, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Cancel"));
  gtk_widget_show (radiobutton6);
  gtk_box_pack_start (GTK_BOX (hbox13), radiobutton6, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed13), combo1, 104, 144);
  gtk_widget_set_size_request (combo1, 187, 27);
  gtk_container_set_border_width (GTK_CONTAINER (combo1), 3);
  gtk_combo_set_value_in_list (GTK_COMBO (combo1), TRUE, TRUE);
  gtk_combo_set_case_sensitive (GTK_COMBO (combo1), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1), TRUE);
  combo1_items = g_list_append (combo1_items, (gpointer) _("Outside"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Interior"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Covered"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_show (combo_entry1);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry1), 8226);

  label79 = gtk_label_new (_("parking_ID"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed13), label79, 16, 32);
  gtk_widget_set_size_request (label79, 72, 16);

  label78 = gtk_label_new (_("parking_name"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed13), label78, 8, 72);
  gtk_widget_set_size_request (label78, 96, 16);

  label71 = gtk_label_new (_("address"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed13), label71, 16, 112);
  gtk_widget_set_size_request (label71, 64, 16);

  label77 = gtk_label_new (_("parking_type"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed13), label77, 0, 152);
  gtk_widget_set_size_request (label77, 96, 16);

  label72 = gtk_label_new (_("ability"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed13), label72, 24, 192);
  gtk_widget_set_size_request (label72, 56, 16);

  label73 = gtk_label_new (_("opening_hours"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed13), label73, -24, 232);
  gtk_widget_set_size_request (label73, 104, 16);

  label74 = gtk_label_new (_("pricing"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed13), label74, 24, 272);
  gtk_widget_set_size_request (label74, 56, 16);

  Modify_parking = gtk_button_new ();
  gtk_widget_show (Modify_parking);
  gtk_fixed_put (GTK_FIXED (fixed13), Modify_parking, 640, 432);
  gtk_widget_set_size_request (Modify_parking, 104, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (Modify_parking), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox8), image14, FALSE, FALSE, 0);

  label145 = gtk_label_new_with_mnemonic (_("Modify"));
  gtk_widget_show (label145);
  gtk_box_pack_start (GTK_BOX (hbox8), label145, FALSE, FALSE, 0);

  label6 = gtk_label_new (_("Modify a parking"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label6);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed18);

  label149 = gtk_label_new (_("label149"));
  gtk_widget_show (label149);
  gtk_fixed_put (GTK_FIXED (fixed18), label149, 288, 552);
  gtk_widget_set_size_request (label149, 57, 17);

  label147 = gtk_label_new (_("Parking"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed18), label147, 488, 112);
  gtk_widget_set_size_request (label147, 57, 17);

  combo3 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo3)->popwin),
                     "GladeParentKey", combo3);
  gtk_widget_show (combo3);
  gtk_fixed_put (GTK_FIXED (fixed18), combo3, 552, 104);
  gtk_widget_set_size_request (combo3, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo3), TRUE);

  combo_entry3 = GTK_COMBO (combo3)->entry;
  gtk_widget_show (combo_entry3);
  gtk_entry_set_invisible_char (GTK_ENTRY (combo_entry3), 8226);

  label148 = gtk_label_new (_("Select an agent"));
  gtk_widget_show (label148);
  gtk_fixed_put (GTK_FIXED (fixed18), label148, 456, 168);
  gtk_widget_set_size_request (label148, 104, 16);

  combo4 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo4)->popwin),
                     "GladeParentKey", combo4);
  gtk_widget_show (combo4);
  gtk_fixed_put (GTK_FIXED (fixed18), combo4, 568, 160);
  gtk_widget_set_size_request (combo4, 187, 27);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo4), TRUE);

  entry26 = GTK_COMBO (combo4)->entry;
  gtk_widget_show (entry26);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed18), treeview5, 880, 88);
  gtk_widget_set_size_request (treeview5, 300, 200);

  Assign = gtk_button_new ();
  gtk_widget_show (Assign);
  gtk_fixed_put (GTK_FIXED (fixed18), Assign, 536, 232);
  gtk_widget_set_size_request (Assign, 88, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Assign), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label157 = gtk_label_new_with_mnemonic (_("Assign"));
  gtk_widget_show (label157);
  gtk_box_pack_start (GTK_BOX (hbox11), label157, FALSE, FALSE, 0);

  Remove = gtk_button_new ();
  gtk_widget_show (Remove);
  gtk_fixed_put (GTK_FIXED (fixed18), Remove, 712, 232);
  gtk_widget_set_size_request (Remove, 88, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Remove), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label158 = gtk_label_new_with_mnemonic (_("Remove"));
  gtk_widget_show (label158);
  gtk_box_pack_start (GTK_BOX (hbox12), label158, FALSE, FALSE, 0);

  label146 = gtk_label_new (_("Assign an agent"));
  gtk_widget_show (label146);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label146);

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed19);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview3, 568, 160);
  gtk_widget_set_size_request (treeview3, 300, 200);

  label164 = gtk_label_new (_("label164"));
  gtk_widget_show (label164);
  gtk_fixed_put (GTK_FIXED (fixed19), label164, 208, 584);
  gtk_widget_set_size_request (label164, 57, 17);

  label150 = gtk_label_new (_("Assign or remove an agent"));
  gtk_widget_show (label150);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 6), label150);

  g_signal_connect ((gpointer) Display, "clicked",
                    G_CALLBACK (on_Display_clicked),
                    NULL);
  g_signal_connect ((gpointer) Delete, "clicked",
                    G_CALLBACK (on_Delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modify, "clicked",
                    G_CALLBACK (on_Modify_clicked),
                    NULL);
  g_signal_connect ((gpointer) Add, "clicked",
                    G_CALLBACK (on_Add_clicked),
                    NULL);
  g_signal_connect ((gpointer) Add_parking, "clicked",
                    G_CALLBACK (on_Add_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Search, "clicked",
                    G_CALLBACK (on_Search_clicked),
                    NULL);
  g_signal_connect ((gpointer) Search_parking, "clicked",
                    G_CALLBACK (on_Search_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modify_parking, "clicked",
                    G_CALLBACK (on_Modify_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Assign, "clicked",
                    G_CALLBACK (on_Assign_clicked),
                    NULL);
  g_signal_connect ((gpointer) Remove, "clicked",
                    G_CALLBACK (on_Remove_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Parking_managment_nidhal_, Parking_managment_nidhal_, "Parking_managment_nidhal_");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label119, "label119");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image1, "image1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label32, "label32");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Display, "Display");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image15, "image15");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label154, "label154");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Delete, "Delete");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image9, "image9");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label140, "label140");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Modify, "Modify");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image10, "image10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label141, "label141");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Add, "Add");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image8, "image8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label139, "label139");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Parking_managment, "Parking_managment");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal1, "textentrynidhal1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal3, "textentrynidhal3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal6, "textentrynidhal6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal7, "textentrynidhal7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, spinnidhal5, "spinnidhal5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image2, "image2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label155, "label155");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label24, "label24");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label25, "label25");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label26, "label26");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label27, "label27");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label29, "label29");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label28, "label28");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal2, "textentrynidhal2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label23, "label23");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Add_parking, "Add_parking");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image7, "image7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label138, "label138");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, comboboxnidhal4, "comboboxnidhal4");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label118, "label118");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label2, "label2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label120, "label120");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label97, "label97");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image3, "image3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton8, "checkbutton8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton9, "checkbutton9");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton10, "checkbutton10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo5, "combo5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Search, "Search");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image16, "image16");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label156, "label156");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label3, "label3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label135, "label135");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label134, "label134");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label159, "label159");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image19, "image19");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton11, "checkbutton11");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton12, "checkbutton12");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton13, "checkbutton13");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton14, "checkbutton14");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo6, "combo6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry33, "entry33");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Search_parking, "Search_parking");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image22, "image22");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label163, "label163");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, button20, "button20");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image20, "image20");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label161, "label161");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label124, "label124");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label123, "label123");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image6, "image6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label70, "label70");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label79, "label79");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label78, "label78");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label71, "label71");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label77, "label77");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label72, "label72");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label73, "label73");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label74, "label74");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Modify_parking, "Modify_parking");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image14, "image14");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label145, "label145");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label6, "label6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label149, "label149");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label147, "label147");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo3, "combo3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo_entry3, "combo_entry3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label148, "label148");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo4, "combo4");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Assign, "Assign");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image17, "image17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label157, "label157");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Remove, "Remove");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image18, "image18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label158, "label158");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label146, "label146");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label164, "label164");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label150, "label150");

  return Parking_managment_nidhal_;
}

