/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Parking_managment_nidhal_ (void)
{
  GtkWidget *Parking_managment_nidhal_;
  GtkWidget *notebook1;
  GtkWidget *fixed7;
  GtkWidget *textentrynidhal1;
  GtkWidget *textentrynidhal3;
  GtkWidget *textentrynidhal6;
  GtkWidget *textentrynidhal7;
  GtkObject *spinnidhal5_adj;
  GtkWidget *spinnidhal5;
  GtkWidget *image2;
  GtkWidget *label155;
  GtkWidget *hbox14;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label29;
  GtkWidget *label28;
  GtkWidget *textentrynidhal2;
  GtkWidget *label118;
  GtkWidget *comboboxentry1;
  GtkWidget *label23;
  GtkWidget *Add_parking;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image7;
  GtkWidget *label138;
  GtkWidget *label2;
  GtkWidget *fixed12;
  GtkWidget *label97;
  GtkWidget *entry25;
  GtkWidget *image3;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *treeview1;
  GtkWidget *hbox15;
  GtkWidget *checkbutton7;
  GtkWidget *hbox16;
  GtkWidget *checkbutton8;
  GtkWidget *hbox17;
  GtkWidget *checkbutton9;
  GtkWidget *hbox18;
  GtkWidget *checkbutton10;
  GtkWidget *combo5;
  GList *combo5_items = NULL;
  GtkWidget *entry29;
  GtkWidget *label120;
  GtkWidget *Search;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image16;
  GtkWidget *label156;
  GtkWidget *button23;
  GtkWidget *alignment18;
  GtkWidget *hbox29;
  GtkWidget *image25;
  GtkWidget *label186;
  GtkWidget *label3;
  GtkWidget *fixed21;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry21;
  GtkWidget *entry22;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label165;
  GtkWidget *hbox26;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *label166;
  GtkWidget *label167;
  GtkWidget *label168;
  GtkWidget *label169;
  GtkWidget *label170;
  GtkWidget *label171;
  GtkWidget *label172;
  GtkWidget *label185;
  GtkWidget *combo1;
  GtkWidget *button22;
  GtkWidget *alignment17;
  GtkWidget *hbox28;
  GtkWidget *image24;
  GtkWidget *label174;
  GtkWidget *button21;
  GtkWidget *alignment16;
  GtkWidget *hbox27;
  GtkWidget *image23;
  GtkWidget *label173;
  GtkWidget *label6;
  GtkWidget *fixed18;
  GtkWidget *treeview5;
  GtkWidget *entry30;
  GtkWidget *entry31;
  GtkWidget *label147;
  GtkWidget *label148;
  GtkWidget *Assign;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label157;
  GtkWidget *label149;
  GtkWidget *button24;
  GtkWidget *alignment19;
  GtkWidget *hbox30;
  GtkWidget *image26;
  GtkWidget *label187;
  GtkWidget *label146;

  Parking_managment_nidhal_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Parking_managment_nidhal_), _("window"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Parking_managment_nidhal_), notebook1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  textentrynidhal1 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal1);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal1, 104, 24);
  gtk_widget_set_size_request (textentrynidhal1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal1), 8226);

  textentrynidhal3 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal3);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal3, 104, 104);
  gtk_widget_set_size_request (textentrynidhal3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal3), 8226);

  textentrynidhal6 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal6);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal6, 112, 224);
  gtk_widget_set_size_request (textentrynidhal6, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal6), 8226);

  textentrynidhal7 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal7);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal7, 112, 264);
  gtk_widget_set_size_request (textentrynidhal7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal7), 8226);

  spinnidhal5_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinnidhal5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinnidhal5_adj), 1, 0);
  gtk_widget_show (spinnidhal5);
  gtk_fixed_put (GTK_FIXED (fixed7), spinnidhal5, 112, 184);
  gtk_widget_set_size_request (spinnidhal5, 160, 27);

  image2 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed7), image2, 920, 64);
  gtk_widget_set_size_request (image2, 192, 200);
  gtk_misc_set_alignment (GTK_MISC (image2), 1, 1);

  label155 = gtk_label_new (_("Add a parking"));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed7), label155, 872, 8);
  gtk_widget_set_size_request (label155, 112, 16);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_fixed_put (GTK_FIXED (fixed7), hbox14, 736, 528);
  gtk_widget_set_size_request (hbox14, 32, 16);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Confirm"));
  gtk_widget_show (radiobutton7);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton7, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Cancel"));
  gtk_widget_show (radiobutton8);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton8, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  label24 = gtk_label_new (_("parking_name"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 8, 72);
  gtk_widget_set_size_request (label24, 96, 16);

  label25 = gtk_label_new (_("address"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 16, 104);
  gtk_widget_set_size_request (label25, 64, 16);

  label26 = gtk_label_new (_("parking_type"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 0, 152);
  gtk_widget_set_size_request (label26, 96, 16);

  label27 = gtk_label_new (_("ability"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed7), label27, 24, 192);
  gtk_widget_set_size_request (label27, 56, 16);

  label29 = gtk_label_new (_("pricing"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 24, 272);
  gtk_widget_set_size_request (label29, 56, 16);

  label28 = gtk_label_new (_("opening_hours"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed7), label28, 0, 232);
  gtk_widget_set_size_request (label28, 104, 16);

  textentrynidhal2 = gtk_entry_new ();
  gtk_widget_show (textentrynidhal2);
  gtk_fixed_put (GTK_FIXED (fixed7), textentrynidhal2, 112, 64);
  gtk_widget_set_size_request (textentrynidhal2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textentrynidhal2), 8226);

  label118 = gtk_label_new (_("label118"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed7), label118, 104, 600);
  gtk_widget_set_size_request (label118, 472, 32);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry1, 112, 144);
  gtk_widget_set_size_request (comboboxentry1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Outside"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Interior"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Covered"));

  label23 = gtk_label_new (_("parking_ID"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed7), label23, 16, 32);
  gtk_widget_set_size_request (label23, 72, 16);

  Add_parking = gtk_button_new ();
  gtk_widget_show (Add_parking);
  gtk_fixed_put (GTK_FIXED (fixed7), Add_parking, 760, 576);
  gtk_widget_set_size_request (Add_parking, 88, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Add_parking), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox1), image7, FALSE, FALSE, 0);

  label138 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label138);
  gtk_box_pack_start (GTK_BOX (hbox1), label138, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Add a parking"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed12);

  label97 = gtk_label_new (_("Parking display"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed12), label97, 800, 8);
  gtk_widget_set_size_request (label97, 120, 16);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed12), entry25, 720, 64);
  gtk_widget_set_size_request (entry25, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  image3 = create_pixmap (Parking_managment_nidhal_, "logo 1 parking.png");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed12), image3, 96, 176);
  gtk_widget_set_size_request (image3, 200, 200);
  gtk_misc_set_alignment (GTK_MISC (image3), 1, 1);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed12), entry27, 432, 56);
  gtk_widget_set_size_request (entry27, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed12), entry28, 432, 112);
  gtk_widget_set_size_request (entry28, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview1, 552, 224);
  gtk_widget_set_size_request (treeview1, 344, 240);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox15, 280, 64);
  gtk_widget_set_size_request (hbox15, 16, 16);

  checkbutton7 = gtk_check_button_new_with_mnemonic (_("parking_ID"));
  gtk_widget_show (checkbutton7);
  gtk_box_pack_start (GTK_BOX (hbox15), checkbutton7, FALSE, FALSE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox16, 296, 120);
  gtk_widget_set_size_request (hbox16, 16, 16);

  checkbutton8 = gtk_check_button_new_with_mnemonic (_("parking_name"));
  gtk_widget_show (checkbutton8);
  gtk_box_pack_start (GTK_BOX (hbox16), checkbutton8, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox17, 624, 72);
  gtk_widget_set_size_request (hbox17, 16, 16);

  checkbutton9 = gtk_check_button_new_with_mnemonic (_("address"));
  gtk_widget_show (checkbutton9);
  gtk_box_pack_start (GTK_BOX (hbox17), checkbutton9, FALSE, FALSE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_fixed_put (GTK_FIXED (fixed12), hbox18, 640, 120);
  gtk_widget_set_size_request (hbox18, 16, 16);

  checkbutton10 = gtk_check_button_new_with_mnemonic (_("parking_type"));
  gtk_widget_show (checkbutton10);
  gtk_box_pack_start (GTK_BOX (hbox18), checkbutton10, FALSE, FALSE, 0);

  combo5 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo5)->popwin),
                     "GladeParentKey", combo5);
  gtk_widget_show (combo5);
  gtk_fixed_put (GTK_FIXED (fixed12), combo5, 752, 112);
  gtk_widget_set_size_request (combo5, 187, 27);
  gtk_container_set_border_width (GTK_CONTAINER (combo5), 3);
  gtk_combo_set_value_in_list (GTK_COMBO (combo5), TRUE, TRUE);
  gtk_combo_set_case_sensitive (GTK_COMBO (combo5), TRUE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo5), TRUE);
  combo5_items = g_list_append (combo5_items, (gpointer) _("Outside"));
  combo5_items = g_list_append (combo5_items, (gpointer) _("Interior"));
  combo5_items = g_list_append (combo5_items, (gpointer) _("Covered"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo5), combo5_items);
  g_list_free (combo5_items);

  entry29 = GTK_COMBO (combo5)->entry;
  gtk_widget_show (entry29);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  label120 = gtk_label_new (_("label120"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed12), label120, 104, 657);
  gtk_widget_set_size_request (label120, 209, 16);

  Search = gtk_button_new ();
  gtk_widget_show (Search);
  gtk_fixed_put (GTK_FIXED (fixed12), Search, 1000, 72);
  gtk_widget_set_size_request (Search, 96, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (Search), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox10), image16, FALSE, FALSE, 0);

  label156 = gtk_label_new_with_mnemonic (_("Search"));
  gtk_widget_show (label156);
  gtk_box_pack_start (GTK_BOX (hbox10), label156, FALSE, FALSE, 0);

  button23 = gtk_button_new ();
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed12), button23, 1000, 136);
  gtk_widget_set_size_request (button23, 74, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button23), alignment18);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox29);

  image25 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox29), image25, FALSE, FALSE, 0);

  label186 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label186);
  gtk_box_pack_start (GTK_BOX (hbox29), label186, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Parking display"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed21);
  gtk_widget_set_size_request (fixed21, 776, 568);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed21), entry17, 104, 24);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed21), entry18, 104, 64);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed21), entry19, 104, 104);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed21), entry21, 104, 224);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed21), entry22, 104, 264);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  spinbutton2_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed21), spinbutton2, 104, 184);
  gtk_widget_set_size_request (spinbutton2, 152, 32);

  label165 = gtk_label_new (_("Modify a parking"));
  gtk_widget_show (label165);
  gtk_fixed_put (GTK_FIXED (fixed21), label165, 416, 0);
  gtk_widget_set_size_request (label165, 120, 16);

  hbox26 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox26);
  gtk_fixed_put (GTK_FIXED (fixed21), hbox26, 624, 400);
  gtk_widget_set_size_request (hbox26, 32, 16);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("confirm"));
  gtk_widget_show (radiobutton5);
  gtk_box_pack_start (GTK_BOX (hbox26), radiobutton5, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("cancel"));
  gtk_widget_show (radiobutton6);
  gtk_box_pack_start (GTK_BOX (hbox26), radiobutton6, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  label166 = gtk_label_new (_("parking_ID"));
  gtk_widget_show (label166);
  gtk_fixed_put (GTK_FIXED (fixed21), label166, 16, 32);
  gtk_widget_set_size_request (label166, 72, 16);

  label167 = gtk_label_new (_("parking_name"));
  gtk_widget_show (label167);
  gtk_fixed_put (GTK_FIXED (fixed21), label167, 8, 72);
  gtk_widget_set_size_request (label167, 96, 16);

  label168 = gtk_label_new (_("address"));
  gtk_widget_show (label168);
  gtk_fixed_put (GTK_FIXED (fixed21), label168, 16, 112);
  gtk_widget_set_size_request (label168, 64, 16);

  label169 = gtk_label_new (_("parking_type"));
  gtk_widget_show (label169);
  gtk_fixed_put (GTK_FIXED (fixed21), label169, 0, 152);
  gtk_widget_set_size_request (label169, 96, 16);

  label170 = gtk_label_new (_("ability"));
  gtk_widget_show (label170);
  gtk_fixed_put (GTK_FIXED (fixed21), label170, 24, 192);
  gtk_widget_set_size_request (label170, 56, 16);

  label171 = gtk_label_new (_("opening_hours"));
  gtk_widget_show (label171);
  gtk_fixed_put (GTK_FIXED (fixed21), label171, -24, 232);
  gtk_widget_set_size_request (label171, 104, 16);

  label172 = gtk_label_new (_("pricing"));
  gtk_widget_show (label172);
  gtk_fixed_put (GTK_FIXED (fixed21), label172, 24, 272);
  gtk_widget_set_size_request (label172, 56, 16);

  label185 = gtk_label_new (_("label185"));
  gtk_widget_show (label185);
  gtk_fixed_put (GTK_FIXED (fixed21), label185, 0, 416);
  gtk_widget_set_size_request (label185, 408, 64);

  combo1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed21), combo1, 104, 144);
  gtk_widget_set_size_request (combo1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("Outside"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("Interior"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("Covered"));

  button22 = gtk_button_new ();
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed21), button22, 288, 24);
  gtk_widget_set_size_request (button22, 74, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button22), alignment17);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox28);

  image24 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox28), image24, FALSE, FALSE, 0);

  label174 = gtk_label_new_with_mnemonic (_("search"));
  gtk_widget_show (label174);
  gtk_box_pack_start (GTK_BOX (hbox28), label174, FALSE, FALSE, 0);

  button21 = gtk_button_new ();
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed21), button21, 640, 432);
  gtk_widget_set_size_request (button21, 104, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button21), alignment16);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox27);

  image23 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox27), image23, FALSE, FALSE, 0);

  label173 = gtk_label_new_with_mnemonic (_("Modify"));
  gtk_widget_show (label173);
  gtk_box_pack_start (GTK_BOX (hbox27), label173, FALSE, FALSE, 0);

  label6 = gtk_label_new (_("Modify a parking"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label6);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed18);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed18), treeview5, 232, 208);
  gtk_widget_set_size_request (treeview5, 740, 216);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed18), entry30, 560, 112);
  gtk_widget_set_size_request (entry30, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed18), entry31, 568, 160);
  gtk_widget_set_size_request (entry31, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  label147 = gtk_label_new (_("Select a parking from his id: parking_ID"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed18), label147, 272, 113);
  gtk_widget_set_size_request (label147, 273, 16);

  label148 = gtk_label_new (_("Select an agent from his id: id_parking"));
  gtk_widget_show (label148);
  gtk_fixed_put (GTK_FIXED (fixed18), label148, 256, 168);
  gtk_widget_set_size_request (label148, 304, 16);

  Assign = gtk_button_new ();
  gtk_widget_show (Assign);
  gtk_fixed_put (GTK_FIXED (fixed18), Assign, 768, 160);
  gtk_widget_set_size_request (Assign, 88, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Assign), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label157 = gtk_label_new_with_mnemonic (_("Assign"));
  gtk_widget_show (label157);
  gtk_box_pack_start (GTK_BOX (hbox11), label157, FALSE, FALSE, 0);

  label149 = gtk_label_new (_("label149"));
  gtk_widget_show (label149);
  gtk_fixed_put (GTK_FIXED (fixed18), label149, 64, 544);
  gtk_widget_set_size_request (label149, 376, 64);

  button24 = gtk_button_new ();
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed18), button24, 744, 112);
  gtk_widget_set_size_request (button24, 74, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button24), alignment19);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox30);

  image26 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox30), image26, FALSE, FALSE, 0);

  label187 = gtk_label_new_with_mnemonic (_("search"));
  gtk_widget_show (label187);
  gtk_box_pack_start (GTK_BOX (hbox30), label187, FALSE, FALSE, 0);

  label146 = gtk_label_new (_("Assign an agent"));
  gtk_widget_show (label146);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label146);

  g_signal_connect ((gpointer) Add_parking, "clicked",
                    G_CALLBACK (on_Add_parking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Search, "clicked",
                    G_CALLBACK (on_Search_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_button23_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_button22_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);
  g_signal_connect ((gpointer) Assign, "clicked",
                    G_CALLBACK (on_Assign_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_button24_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Parking_managment_nidhal_, Parking_managment_nidhal_, "Parking_managment_nidhal_");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal1, "textentrynidhal1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal3, "textentrynidhal3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal6, "textentrynidhal6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal7, "textentrynidhal7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, spinnidhal5, "spinnidhal5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image2, "image2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label155, "label155");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label24, "label24");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label25, "label25");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label26, "label26");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label27, "label27");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label29, "label29");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label28, "label28");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, textentrynidhal2, "textentrynidhal2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label118, "label118");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label23, "label23");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Add_parking, "Add_parking");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image7, "image7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label138, "label138");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label2, "label2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label97, "label97");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image3, "image3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton7, "checkbutton7");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton8, "checkbutton8");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton9, "checkbutton9");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, checkbutton10, "checkbutton10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo5, "combo5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label120, "label120");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Search, "Search");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image16, "image16");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label156, "label156");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, button23, "button23");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image25, "image25");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label186, "label186");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label3, "label3");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label165, "label165");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label166, "label166");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label167, "label167");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label168, "label168");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label169, "label169");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label170, "label170");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label171, "label171");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label172, "label172");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label185, "label185");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, button22, "button22");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image24, "image24");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label174, "label174");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, button21, "button21");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image23, "image23");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label173, "label173");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label6, "label6");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label147, "label147");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label148, "label148");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, Assign, "Assign");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image17, "image17");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label157, "label157");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label149, "label149");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, button24, "button24");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, image26, "image26");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label187, "label187");
  GLADE_HOOKUP_OBJECT (Parking_managment_nidhal_, label146, "label146");

  return Parking_managment_nidhal_;
}

